### ISSUE TITLE
Could we customize the keyboard style?

### ISSUE THREAD

**Issue by oozliuoo** [MartyWallace/vue-keyboard#12]
Are there anyways to style the keyboard such that the buttons would be larger to fit in the screen? Right now it is somehow too small for my scenario.

Thanks!

**Comment by MartyWallace** [comment]
@oozliuoo Of course you can - are you having any issues customising them at the moment? Something like this should be fine:

```
#app .vue-keyboard button {
    padding: 24px 30px;
}
````
