### ISSUE TITLE
Possible for SmartPhone?

### ISSUE THREAD

**Issue by thearabbit** [MartyWallace/vue-keyboard#17]
Possible for SmartPhone?

**Comment by MartyWallace** [comment]
Happy to help out but could you add more information? It works on a touch device currently and you can easily change the CSS to better suit smaller devices - is there something else missing or that you think should be different?

**Comment by thearabbit** [comment]
Thanks for your reply, I would like to build `Khmer Keyboard` on `iOS`.
It is possible?

**Comment by MartyWallace** [comment]
You can definitely use the keyboard on a website viewed on iOS.

**Comment by thearabbit** [comment]
Sorry I don't understand about `...website viewed on iOS`

**Comment by MartyWallace** [comment]
When you build a HTML5 application using this component, it functions correctly on iOS.
