### ISSUE TITLE
CSS class for certain button.

### ISSUE THREAD

**Issue by Wolrab1** [MartyWallace/vue-keyboard#23]
I can see in the component the option to pass btn.type to the class property. 

How do I pass this via the :layouts prop?

I'd like to set a class for a particular button.

**Comment by MartyWallace** [comment]
@Wolrab1 You can see [here](https://github.com/MartyWallace/vue-keyboard/blob/master/src/keyboard.vue#L203-L204) that I attach `data-text` and `data-action` attributes to every button, which you could use to target individual buttons with CSS with something like:

```css
.vue-keyboard-key[data-text="b"] {
  color: red;
}
```

Which would style only the button containing the text `b`.
