### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ryanweal** [MartyWallace/vue-keyboard#6]
Hello, I am considering to use this in a project... I am curious what is the license? I see a lot of MIT license for Vue.js projects but nothing is explicitly specified here or on the demos site.

Thanks for your time!

**Comment by ryanweal** [comment]
Ah, I see it is listed in the bower.json file as MIT license. Would still be good to also include a license file so it shows on the GitHub profile. Cheers.

**Comment by MartyWallace** [comment]
@ryanweal Hi, you're right I'll add that now! Sorry I didn't see this earlier, I never received a notification :(

**Comment by MartyWallace** [comment]
bdd11ee141285a99bdea1966de3f4df7a23f2a04
